### ISSUE TITLE
p_sum error message

### ISSUE THREAD

**Issue by cometta** [dubovikmaster/parallel-pandas#9]
i'm using parallel-pandas 0.6.3
```
>>> import numpy as np
>>> from parallel_pandas import ParallelPandas
>>>
>>> #initialize parallel-pandas
>>> ParallelPandas.initialize(n_cpu=16, split_factor=4, disable_pr_bar=True)
>>>
>>> # create big DataFrame
>>> df = pd.DataFrame(np.random.random((1_000_000, 100)))
>>>
>>> res = df.sum()
>>> res = df.p_sum()
```

i get below error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/site-packages/parallel_pandas/core/parallel_dataframe.py", line 810, in p_sum
    return self._parallel_min_count_stat_func(data, name=name, axis=axis,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/site-packages/parallel_pandas/core/parallel_dataframe.py", line 799, in _parallel_min_count_stat_func
    result = progress_imap(
             ^^^^^^^^^^^^^^
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/site-packages/parallel_pandas/core/progress_imap.py", line 127, in progress_imap
    result = _do_parallel(func, tasks, initializer, initargs, n_cpu, total, disable, show_vmem, q, executor, desc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/site-packages/parallel_pandas/core/progress_imap.py", line 111, in _do_parallel
    result.append(next(iter_result))
                  ^^^^^^^^^^^^^^^^^
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/multiprocessing/pool.py", line 873, in next
    raise value
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/site-packages/parallel_pandas/core/parallel_dataframe.py", line 791, in _min_count_stat_func
    return progress_udf_wrapper(closure, workers_queue, 1)()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/site-packages/parallel_pandas/core/progress_imap.py", line 52, in wrapped_udf
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/home/organization/miniconda3/envs/spark_benchmark/lib/python3.11/site-packages/parallel_pandas/core/parallel_dataframe.py", line 787, in closure
    return df._min_count_stat_function(name, self.get_nanops_arg(name), axis, skipna, level, numeric_only,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NDFrame._min_count_stat_function() takes from 3 to 7 positional arguments but 8 were given
```
can advice?

**Comment by dubovikmaster** [comment]
Fixed in 0.6.4
